version: "3.9"

services:
  librarydb:
    image: mysql
    container_name: librarydb_container
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: Libraby_DB
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234library
    restart: always
    ports:
      - "3030:3306"
    networks:
      - web_network

  phpmyadminlibrary:
    image: phpmyadmin:latest
    container_name: phpmyadmin_library
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "5959:80"
    networks:
      - web_network
  libraryweb:
    build: ./nextjs-library
    container_name: libraryweb_container
    restart: always
    ports:
      - "8080:3000"
    networks:
      - web_network