version: "3.9"

services:
  librarydb:
    image: mysql
    container_name: librarydb_container
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: Libraby_DB
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234library
    restart: always
    ports:
      - "3030:3306"
    networks:
      - web_network

  phpmyadminlibrary:
    image: phpmyadmin:latest
    container_name: phpmyadmin_library
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "5959:80"
    networks:
      - web_network
  # libraryweb:
  #   build: ./nextjs-library
  #   image: libraryweb:1.0
  #   container_name: libraryweb_container
  #   restart: always
  #   ports:
  #     - "8080:3000"
  #   networks:
  #     - web_network
  libraryapi:
    depends_on:
      - librarydb
    build: ./borrow_book_api
    image: library_api:1.0
    container_name: librayry_api
    restart: always
    ports:
      - "5050:5050"
    networks:
      - web_network

networks:
  web_network:
    name: tamnmhee
    driver: bridge
